spring.application.name=AppModule
spring.datasource.url=jdbc:mysql://localhost:3306/book_store?useSSL=false
spring.datasource.username=root
spring.datasource.password=root

# [TODO:] Get application.properties file out from source files
#spring.datasource.url=jdbc:mysql://bookstore-db.cch2g8648mpy.us-east-1.rds.amazonaws.com:3306/bookstore-db?useSSL=false
#spring.datasource.username=admin
#spring.datasource.password=password

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

# Max file size (individual file limit)
spring.servlet.multipart.max-file-size=10MB
